version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "America/Los_Angeles"
    target-branch: "main"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
